:::{#exr-simulation}
## Dice Rolls Simulation

You roll two six-sided dice 1000 times. Assume that the dice are fair and that the trials are independent. In how many games would you expect to get a sum greater than 10?

- Event $A$: Estimate the probability of getting a sum greater than 10.
- Event $B$: Estimate the probability of getting a sum of 7 with the first die being 3.
- Event $C$: Estimate the probability of getting a sum greater than 7 and the first die being 5.
- Event $D$: Estimate the probability of getting a sum of greater than 8 and the first roll is smaller or equal to the second roll.

Use [Exercise 3.3](https://febse.github.io/stat2024/03-Probability.html#discrete-sample-spaces) as a starting point.

:::
:::{.callout-info collapse="true"}
## Sample Space (click to expand)

We can consider a sample space of ordered pairs (first die, second die) with 36 equally likely outcomes. The probability of each outcome is $1/36$.

The sample space is:

$$
\Omega = \left\{
    \begin{array}{cccccc}
        (1,1) & (1, 2) & (1, 3) & (1, 4) & (1, 5) & (1, 6) \\
        (2,1) & (2, 2) & (2, 3) & (2, 4) & (2, 5) & (2, 6) \\
        (3,1) & (3, 2) & (3, 3) & (3, 4) & (3, 5) & (3, 6) \\
        (4,1) & (4, 2) & (4, 3) & (4, 4) & (4, 5) & (4, 6) \\
        (5,1) & (5, 2) & (5, 3) & (5, 4) & (5, 5) & (5, 6) \\
        (6,1) & (6, 2) & (6, 3) & (6, 4) & (6, 5) & (6, 6) \\
    \end{array}
\right\}
$$
:::
:::{.callout-info collapse="true"}
## Events (click to expand)

Let $A$ be the event that the sum of the dice is greater than 10. The event $A$ is:

$$
A = \left\{
    \begin{array}{cccccc}
        (5,6) & (6,5) & (6,6) \\
    \end{array}
\right\}
$$

It has 3 outcomes, so the probability of $A$ is $3/36 = 1/12$.

Let $B$ be the event that the sum of the dice is 7 and the first die is 3. The event $B$ is:

$$
B = \left\{
    \begin{array}{c}
        (3,4) \\
    \end{array}
\right\}
$$

It has 1 outcome, so the probability of $B$ is $1/36$.

Let $C$ be the event that the sum of the dice is greater than 7 and the first die is 5. The event $C$ is:

$$
C = \left\{
    \begin{array}{cccc}
        (5,3) & (5,4) & (5,5) & (5,6) \\
    \end{array}
\right\}
$$

It has 4 outcomes, so the probability of $C$ is $4/36 = 1/9$.

Let $D$ be the event that the sum of the dice is greater than 8 and the first die is smaller or equal to the second die. The event $D$ is:

$$
D = \left\{
    \begin{array}{cccc}
        (6, 6) & (5, 6) & (4, 6) & (3, 6) \\
        (5, 5) & (4, 5) \\
    \end{array}
\right\}
$$

It has 6 outcomes, so the probability of $D$ is $6/36 = 1/6$.

:::


In [60]:
import numpy as np

# First, throw a pair of dice 10 times.
# The result is a 10x2 matrix where each row is one throw.
# The first column is the result of the first die, the second column is the result of the second die.
# Each row corresponds to one repetition of the game

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size=[10, 2])
rolls


array([[5, 1],
       [1, 4],
       [5, 6],
       [6, 4],
       [5, 5],
       [5, 2],
       [5, 4],
       [4, 2],
       [5, 1],
       [4, 3]])

In [59]:
# The following uses the function np.sum()
# Check what it is doing

np.sum(rolls)

70095

In [3]:
np.sum(rolls, axis=0)

array([34, 30])

In [58]:
np.sum(rolls, axis=1)

array([ 5,  7, 10, ...,  9,  7,  5])

In [ ]:
np.sum(rolls, axis=1) > 10

array([False, False, False, False, False,  True, False, False, False,
        True])

In [ ]:
eventA = (np.sum(rolls, axis=1) > 10)
eventA

array([False, False, False, False, False,  True, False, False, False,
        True])

In [72]:
np.sum(eventA)

2

In [73]:
np.mean(eventA)

0.2

In [68]:
print("Event A occurred in", np.sum(eventA), "games.")
print("Event A occurred in", 100 * np.mean(eventA), "percent of the games.")

Event A occurred in 2 games.
Event A occurred in 20.0 percent of the games.


In [ ]:
# Selects the first row of the array (same as above)
rolls[0, :]

array([4, 3])

In [70]:
# Selects the first column of the array (same as above)
rolls[:, 0]

array([5, 1, 5, 6, 5, 5, 5, 4, 5, 4])

In [ ]:
# Selects the second column
rolls[:, 1]

array([4, 1, 3, 4, 3, 2, 4, 3, 3, 3])

In [11]:
rolls[:, 0] > 3

array([ True,  True, False,  True,  True, False,  True, False, False,
       False])

In [ ]:
# Create a new array called eventB that is True if:
# - the first die equals 3
# AND
# - the roll sum is equal to 7
# Hint: Use the & operator (logical AND)
 


In [74]:
# Create a new array called eventC that is True if:
# - the roll sum is greater than 7
# AND
# - the second die is equal to 5



In [ ]:
# Create a new array called eventD that is True if:
# - the roll sum is greater than 8
# AND
# - the first die is smaller or equal to the second die


## The Matching Problem

Some results in probability theory can be confusing and counter-intuitive. A classic example is the matching problem. Consider a room with $n$ dancing couples. If the couples are randomly paired, what is the probability that after the pairing, no one is matched with their original partner?

Imagine that the leads are numbered from 1 to $n$ and the follows are also numbered from 1 to $n$.

The original arrangement of the couples and two possible rearrangements are shown in the table below (for five couples numbered from 0 to 4).

| Leads                  | 0   | 1   | 2   | 3   | 4   | Matches |
| ---------------------- | --- | --- | --- | --- | --- | ------- |
| Follows (original)     | 0   | 1   | 2   | 3   | 4   | 5       |
| Follows (rearranged 1) | 2   | 4   | 1   | 3   | 0   | ?       |
| Follows (rearranged 2) | 0   | 1   | 3   | 4   | 2   | ?       |


We will approach the problem with a simulation. We will randomly pair the couples and count the number of times no one is matched with their original partner. We will then compare the simulation results with the theoretical resulFollows (original)ts.

In [ ]:
n = 5 # Number of pairs
repetitions = 3 # Number of simulations

# Create a list (an array) of integers from 0 to n-1 (corresponding to the partners)

partners = np.arange(n)
partners

array([   0,    1,    2, ..., 1997, 1998, 1999])

In [37]:
# NOTE: code for illustration purposes only

# A single experiment: shuffle the partners and check if there are any matches

partners_shuffled = np.random.permutation(partners)
print("Partners after shuffling:")
partners_shuffled

Partners after shuffling:


array([0, 4, 2, 1, 3])

In [41]:
# If the value in the shuffled array is the same as in the original array, it means that the partners are the same
# as in the original couple

# We can check if there are any matches by comparing the two arrays element-wise

matches = (partners == partners_shuffled)

print("Matches:")

Matches:


In [40]:
# We are interested in the event "No partner gets their original partner".
# 

n_matches = np.sum(matches)

print("Number of matches:", n_matches)

Number of matches: 2


In [ ]:
# Now we can repeat the experiment a large number of times (repetitions) 
# and count how many times there were no matches

# Set the number of matches to zero
no_matches_counter = 0

for i in range(repetitions):
    # Shuffle the partners
    partners_shuffled = np.random.permutation(partners)
    
    # Check if no one got their original partner.
    no_match_in_permutation = np.sum(partners == partners_shuffled) == 0
    
    # If yes, increment the no_matches counter
    if no_match_in_permutation:
        no_matches_counter += 1

print("Number of times (simulations) where no partner got their original partner:", no_matches_counter)
print("Proportion of no partner getting their original partner:", no_matches_counter / repetitions)

Number of times (simulations) where no partner got their original partner: 18420
Proportion of no partner getting their original partner: 0.3684


In [ ]:
# The previous code loops over the number of simulations and counts the number of matches in each simulation
# It uses a for loop and the np.random.permutation() function

# To see what a loop does you can use the print() function to print the value of a variable inside the loop

# np.arange(3) will create an array [0, 1, 2]
for i in range(3):
    print("Simulation", i + 100)


Simulation 100
Simulation 101
Simulation 102


In [55]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
# We will use a variable to count the number of matches in each simulation

# See how this works in a simple example

counter = 0

for i in range(10):
    counter = counter + 1
    print("Counter =", counter)
    
print("Final counter value =", counter)

Counter = 1
Counter = 2
Counter = 3
Counter = 4
Counter = 5
Counter = 6
Counter = 7
Counter = 8
Counter = 9
Counter = 10
Final counter value = 10


In [54]:
# We can choose when to increment the counter by using an if statement

counter = 0

for i in range(10):
    if i % 2 == 0:
        print(i, "is even, incrementing counter")
        counter = counter + 1
    else:
        print(i, "is odd, not incrementing counter")

    print("Counter:", counter)

print("Final counter:", counter)

0 is even, incrementing counter
Counter: 1
1 is odd, not incrementing counter
Counter: 1
2 is even, incrementing counter
Counter: 2
3 is odd, not incrementing counter
Counter: 2
4 is even, incrementing counter
Counter: 3
5 is odd, not incrementing counter
Counter: 3
6 is even, incrementing counter
Counter: 4
7 is odd, not incrementing counter
Counter: 4
8 is even, incrementing counter
Counter: 5
9 is odd, not incrementing counter
Counter: 5
Final counter: 5
