:::{#exr-simulation}
## Dice Rolls Simulation

You roll two six-sided dice 1000 times. Assume that the dice are fair and that the trials are independent. In how many games would you expect to get a sum greater than 10?

- Event $A$: Estimate the probability of getting a sum greater than 10.
- Event $B$: Estimate the probability of getting a sum of 7 with the first die being 3.
- Event $C$: Estimate the probability of getting a sum greater than 7 and the first die being 5.
- Event $D$: Estimate the probability of getting a sum of greater than 8 and the first roll is smaller or equal to the second roll.

Use [Exercise 3.3](https://febse.github.io/stat2024/03-Probability.html#discrete-sample-spaces) as a starting point.

:::
:::{.callout-info collapse="true"}
## Sample Space (click to expand)

We can consider a sample space of ordered pairs (first die, second die) with 36 equally likely outcomes. The probability of each outcome is $1/36$.

The sample space is:

$$
\Omega = \left\{
    \begin{array}{cccccc}
        (1,1) & (1, 2) & (1, 3) & (1, 4) & (1, 5) & (1, 6) \\
        (2,1) & (2, 2) & (2, 3) & (2, 4) & (2, 5) & (2, 6) \\
        (3,1) & (3, 2) & (3, 3) & (3, 4) & (3, 5) & (3, 6) \\
        (4,1) & (4, 2) & (4, 3) & (4, 4) & (4, 5) & (4, 6) \\
        (5,1) & (5, 2) & (5, 3) & (5, 4) & (5, 5) & (5, 6) \\
        (6,1) & (6, 2) & (6, 3) & (6, 4) & (6, 5) & (6, 6) \\
    \end{array}
\right\}
$$
:::
:::{.callout-info collapse="true"}
## Events (click to expand)

Let $A$ be the event that the sum of the dice is greater than 10. The event $A$ is:

$$
A = \left\{
    \begin{array}{cccccc}
        (5,6) & (6,5) & (6,6) \\
    \end{array}
\right\}
$$

It has 3 outcomes, so the probability of $A$ is $3/36 = 1/12$.

Let $B$ be the event that the sum of the dice is 7 and the first die is 3. The event $B$ is:

$$
B = \left\{
    \begin{array}{c}
        (3,4) \\
    \end{array}
\right\}
$$

It has 1 outcome, so the probability of $B$ is $1/36$.

Let $C$ be the event that the sum of the dice is greater than 7 and the first die is 5. The event $C$ is:

$$
C = \left\{
    \begin{array}{cccc}
        (5,3) & (5,4) & (5,5) & (5,6) \\
    \end{array}
\right\}
$$

It has 4 outcomes, so the probability of $C$ is $4/36 = 1/9$.

Let $D$ be the event that the sum of the dice is greater than 8 and the first die is smaller or equal to the second die. The event $D$ is:

$$
D = \left\{
    \begin{array}{cccc}
        (6, 6) & (5, 6) & (4, 6) & (3, 6) \\
        (5, 5) & (4, 5) \\
    \end{array}
\right\}
$$

It has 6 outcomes, so the probability of $D$ is $6/36 = 1/6$.

:::


In [2]:
import numpy as np

# First, throw a pair of dice 10 times.
# The result is a 10x2 matrix where each row is one throw.
# The first column is the result of the first die, the second column is the result of the second die.
# Each row corresponds to one repetition of the game

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size=[10, 2])
rolls


array([[6, 1],
       [5, 3],
       [2, 5],
       [6, 5],
       [2, 3],
       [4, 1],
       [6, 4],
       [1, 4],
       [2, 3],
       [4, 3]])

In [6]:
# The following uses the function np.sum()
# Check what it is doing

np.sum(rolls)

70

In [7]:
np.sum(rolls, axis=0)

array([38, 32])

In [8]:
np.sum(rolls, axis=1)

array([ 7,  8,  7, 11,  5,  5, 10,  5,  5,  7])

In [9]:
# The next operation that we need is array slicing. Run the following code and compare the output to the original rolls array.
# Selects the first row of the array
rolls[0]

array([6, 1])

In [12]:
# Selects the first column of the array (same as above)
rolls[0, :]

array([6, 1])

In [10]:
# Selects the first column

rolls[:, 0]

array([6, 5, 2, 6, 2, 4, 6, 1, 2, 4])

In [11]:
# Selects the second column

rolls[:, 1]

array([1, 3, 5, 5, 3, 1, 4, 4, 3, 3])

In [13]:
# We also need logical comparisons. Run the following code and compare the output to the original rolls array.

rolls > 3


array([[ True, False],
       [ True, False],
       [False,  True],
       [ True,  True],
       [False, False],
       [ True, False],
       [ True,  True],
       [False,  True],
       [False, False],
       [ True, False]])

In [14]:
rolls[:, 0] > 3

array([ True,  True, False,  True, False,  True,  True, False, False,
        True])

In [15]:
np.sum(rolls[:, 0] > 3)

6

In [5]:
# Count the number of occurrences of event A
# For A the sum of the two dice is 10
# You can use the np.sum() function to sum the values in each row
# Then you can compare the result to 10 using the == operator
# The result is a boolean array (True/False) where True means that the sum of the two dice is 10
# You can use the np.sum() function again to count the number of occurrences of True

# In the following, change the condition to check if the sum of the two dice is 10

roll_sum = np.sum(rolls, axis=1)
A = (roll_sum == 12)
np.sum(A)

3

In [ ]:
# In event B the sum is 7 AND the first die is 3
# You can use the & operator to combine two conditions
# The result is a boolean array where True means that both conditions are True
# You can use the np.sum() function to count the number
# of occurrences
# You can access the first column of the matrix using the syntax rolls[:, 0]

# In the following, change the condition to check if the sum of the two dice is 7 AND the first die is 3

B = (roll_sum == 3) & (rolls[:, 1] == 8)

# Count the number of occurrences of event B as in the previous example


In [ ]:
# For event C the sum is greater (>) than 7 AND the first die is 5
# Change the code for event B so that you can count the number of occurrences of event C



In [ ]:
# For event D the sum is greater (>) than 8 AND the first roll is less (<) than the second roll
# To compare the first and second rolls you can use the < operator

# For example the following checks if the first roll is greater than the second roll
# Adapt it and use it to count the number of occurrences of event D

rolls[:, 0] > rolls[:, 1]


array([ True,  True, False,  True, False,  True,  True, False, False,
        True])